/**
 * OTA getprop ingest Worker (write-only).
 *
 * POST /v1/getprop
 *   body: JSON object of getprop/build.prop key->value (the app's parsed props)
 *   - validates ro.build.fingerprint
 *   - idempotently commits OTA/Google/{brand}/{model}/{ro.build.date.utc}/getprop.json
 *     to the data repo via the GitHub Contents API (skips if it already exists)
 *   - does NOT touch timestamps.json (regenerated by scheduled GitHub Actions)
 *
 * Reads (timestamps.json / firmware.json) are NOT served here: the app fetches
 * them directly from cdn.jsdelivr.net.
 */
export interface Env {
  GH_TOKEN: string;       // fine-grained PAT, Contents: R/W on the data repo (secret)
  GH_REPO: string;        // "owner/repo", e.g. "mouseos/ota-archive"
  GH_BRANCH?: string;     // default "main"
  RL?: KVNamespace;       // optional: simple per-IP rate limit
}

const FINGERPRINT_RE = /^[^/]+\/[^/]+\/[^/:]+:[^/]+\/[^/]+\/[^:]+:[^/]+\/[^/]+$/;
const SEG_RE = /^[A-Za-z0-9._-]+$/;

function json(status: number, body: unknown): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "content-type": "application/json; charset=utf-8" },
  });
}

function sanitize(v: unknown): string {
  return String(v ?? "").trim();
}

async function rateLimit(env: Env, ip: string): Promise<boolean> {
  if (!env.RL) return true; // no KV bound -> rely on Cloudflare dashboard rules
  const key = `rl:${ip}`;
  const n = parseInt((await env.RL.get(key)) ?? "0", 10);
  if (n >= 60) return false; // 60 posts / hour / IP
  await env.RL.put(key, String(n + 1), { expirationTtl: 3600 });
  return true;
}

async function ghContents(
  env: Env,
  method: "GET" | "PUT",
  path: string,
  init?: { body?: unknown },
): Promise<Response> {
  const branch = env.GH_BRANCH || "main";
  const url = `https://api.github.com/repos/${env.GH_REPO}/contents/${path}` +
    (method === "GET" ? `?ref=${encodeURIComponent(branch)}` : "");
  return fetch(url, {
    method,
    headers: {
      authorization: `Bearer ${env.GH_TOKEN}`,
      accept: "application/vnd.github+json",
      "user-agent": "ota-archive-worker",
      "x-github-api-version": "2022-11-28",
      ...(method === "PUT" ? { "content-type": "application/json" } : {}),
    },
    body: init?.body ? JSON.stringify(init.body) : undefined,
  });
}

export default {
  async fetch(req: Request, env: Env): Promise<Response> {
    const url = new URL(req.url);
    if (req.method !== "POST" || url.pathname !== "/v1/getprop") {
      return json(404, { error: "not found" });
    }

    const ip = req.headers.get("cf-connecting-ip") ?? "0.0.0.0";
    if (!(await rateLimit(env, ip))) return json(429, { error: "rate limited" });

    let props: Record<string, string>;
    try {
      const parsed = await req.json();
      if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
        return json(400, { error: "body must be a JSON object of props" });
      }
      props = parsed as Record<string, string>;
    } catch {
      return json(400, { error: "invalid JSON" });
    }

    const fingerprint = sanitize(props["ro.build.fingerprint"]);
    const brand = sanitize(props["ro.product.brand"]);
    const model = sanitize(props["ro.product.model"]);
    const utc = sanitize(props["ro.build.date.utc"]);

    if (!FINGERPRINT_RE.test(fingerprint)) {
      return json(400, { error: "invalid ro.build.fingerprint" });
    }
    if (!SEG_RE.test(brand) || !SEG_RE.test(model) || !/^\d+$/.test(utc)) {
      return json(400, { error: "invalid brand/model/ro.build.date.utc" });
    }

    const path = `OTA/Google/${brand}/${model}/${utc}/getprop.json`;

    // idempotent: skip if it already exists
    const head = await ghContents(env, "GET", path);
    if (head.status === 200) {
      return json(200, { status: "exists", path });
    }
    if (head.status !== 404) {
      return json(502, { error: "github read failed", code: head.status });
    }

    const content = btoa(
      unescape(encodeURIComponent(JSON.stringify(props, null, 2) + "\n")),
    );
    const put = await ghContents(env, "PUT", path, {
      body: {
        message: `getprop ${brand}/${model}/${utc}`,
        content,
        branch: env.GH_BRANCH || "main",
      },
    });
    if (put.status === 201) return json(202, { status: "created", path });
    if (put.status === 422) return json(200, { status: "exists", path }); // race
    return json(502, { error: "github write failed", code: put.status });
  },
};
